apiVersion: v1
kind: ServiceAccount
metadata:
  name: step3-ns-sa
  namespace: step3
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: step3-ns-role
  namespace: step3
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: step3-ns-role-binding
  namespace: step3
subjects:
  - kind: ServiceAccount
    name: step3-ns-sa
    namespace: step3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: step3-ns-role
