#@ load("@ytt:overlay", "overlay")
#@data/values

#@overlay/match by=overlay.all
---
backend:
  #@overlay/replace via=lambda left, right: right
  namespace: step4

storage:
  #@overlay/replace via=lambda left, right: right
  address: storage.step4.svc.cluster.local
