apiVersion: v1
kind: ServiceAccount
metadata:
  name: step4-ns-sa
  namespace: step4
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: step4-ns-role
  namespace: step4
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: step4-ns-role-binding
  namespace: step4
subjects:
  - kind: ServiceAccount
    name: step4-ns-sa
    namespace: step4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: step4-ns-role
