---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-frontend
  namespace: step1
  labels:
    app.kubernetes.io/name: go-frontend
    app.kubernetes.io/instance: go-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: go-frontend
  namespace: step1
  labels:
    app.kubernetes.io/name: go-frontend
    app.kubernetes.io/instance: go-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: go-frontend
    app.kubernetes.io/instance: go-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-frontend
  namespace: step1
  labels:
    app.kubernetes.io/name: go-frontend
    app.kubernetes.io/instance: go-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-frontend
      app.kubernetes.io/instance: go-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-frontend
        app.kubernetes.io/instance: go-frontend
    spec:
      serviceAccountName: go-frontend
      securityContext:
        {}
      containers:
        - name: go-frontend
          securityContext:
            {}
          image: ghcr.io/joaopapereira/demo-intro-carvel/frontend@sha256:d7906891ab857157d4ec1d0f4d43c2f1a624cf66c14d829cb2a40aba7c88c345
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          env:
            - name: BACKEND_ADDRESS
              value: backend.step1.svc.cluster.local:8080
          resources:
            {}
